### ISSUE TITLE
Implement engine under-thrust/under-Isp failures in a way that doesn't depend on thrust limiter.

### ISSUE THREAD

**Issue by bfrobin446** [zer0Kerbal/OhScrap#1]
I plan to update the engine failure code to work with non-throttleable engines based on similar failure modes in TestFlight, as briefly discussed at https://github.com/severedsolo/OhScrap/issues/23. Opening a ticket here to provide updates.

**Comment by zer0Kerbal** [comment]
#2 https://github.com/zer0Kerbal/OhScrap/pull/2
recompiling - and updating beta now.
