### ISSUE TITLE
OhScrap window doesn't get hidden when F2 is pressed

### ISSUE THREAD

**Issue by jefferyharrell** [zer0Kerbal/OhScrap#21]
https://i.imgur.com/OuFZEcv.jpg

**Comment by zer0Kerbal** [comment]
@jefferyharrell thank you.

this normally (should) be a simple fix - just need to add one function; that is IIRC 🎗️

**Comment by zer0Kerbal** [comment]
![image](https://user-images.githubusercontent.com/39887717/134792002-34a948a4-7858-4213-a246-1be2618140d0.png)

**Comment by zer0Kerbal** [comment]
is working in 2.2.1.0-beta.
