### ISSUE TITLE
2.2.1.0-Beta-0 📎 

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/OhScrap#38]
- [ ] Two week beta

**Comment by Gordon-Dry** [comment]
The highlighting of a failed part can not be toggled on the PAW anymore. It's just always enabled.

**Comment by Gordon-Dry** [comment]
When trying to radially attach more than 1 retro boosters to tanks, OhScrap! plays that annoying sound mix of FirePager and PhoneVibrator in a loop.
Mostly on the right channel.
FirePager is stereo.
PhoneVibrator is mono.
