### ISSUE TITLE
2.2.1.0 beta: radially attach in VAB - annoying sound mix of FirePager and PhoneVibrator

### ISSUE THREAD

**Issue by Gordon-Dry** [zer0Kerbal/OhScrap#44]
When trying to radially attach more than 1 retro boosters to tanks, OhScrap! plays that annoying sound mix of FirePager and PhoneVibrator in a loop.
Mostly on the right channel.
FirePager is stereo.
PhoneVibrator is mono.

**Comment by Gordon-Dry** [comment]
To troubleshoot I did the following:

1. converted PhoneVibrator to stereo
2. fiddled the files aka. remastered them
3. set them to -6 dB
4. set them all to 44.1 kHz (one of them was 48 kHz)
5. saved all audio files to OGG

Well, the sounds are loaded without issues and played.
But - the annoying playing of both sounds on the right channnel in an overdriven loud way is still a thing.

The more radial parts are to be attached the more instances of that already overdriven sound are crashing the right ear until it starts bleeding.

Setting the OhScrap! audio volume to 0.01 did not help. It's always the same volume.

**Comment by Gordon-Dry** [comment]
Temporary solution is to lower the volume of the 2 affected audio files by 30 dB, so they peak in -36 dB.
And what did I find?
It's (at least) 3 sounds playing the same time, not 2:
"alarm" comes to the list - I did not recognize it before in the audio mayhem because of "PhoneVibrating".

So I guess I don't need to lower the volume of the other 2 sounds by 30 dB, just by 12 dB for all 3 of them.

And this all is temporary ...

**Comment by zer0Kerbal** [comment]
Thank you @Gordon-Dry !
Sound issues are fixed internally - and will be in the next release.
I plan on doing another pass on SYD-OHS shortly - it is on the short list.
