### ISSUE TITLE
English <en-us.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/OhScrap#55]
# Localization - English <en-us.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Milestone: (Project) Localization - English <en-us.cfg>

### GameData

* [ ] add  Localization\[en-us.cfg] 🗃️

### Translation

* [ ] ![English][EN] English <en-us.cfg>

### Documentation

* [ ] Update [readme.md] 🔢
* [ ] Update [release.md] 🧾

### Wiki

* [ ] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[EN]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/EN.png "English"

this file: © All Rights Reserved by zer0Kerbal

**Comment by Gordon-Dry** [comment]
I assume the file should be named en-us.cfg, not us-en.cfg, than this does not happen:
![Screen-2022-10-26_20-19-11](https://user-images.githubusercontent.com/29145213/198106325-84c8497d-f2e8-4533-9019-44f9cf890846.jpg)

But perhaps I'm wrong as the us-en.cgf says
`#OHS_ ***`
but as you can see in the screenshot it demands entries with
`#FND_ ***`

**Comment by zer0Kerbal** [comment]
@Gordon-Dry thank you. I am working on an update that will be out first part of November. Have the 🎃 mods first.

**Comment by zer0Kerbal** [comment]
[en-us.zip](https://github.com/zer0Kerbal/OhScrap/files/9875047/en-us.zip)
advanced copy.
