### ISSUE TITLE
Simplified Chinese (简体中文) <zh-cn.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/OhScrap#63]
# Localization - ![简体中文][CN] Simplified Chinese (简体中文) <zh-cn.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[zh-ch.cfg] 🗃️

### Translation

* [x] ![简体中文][CN] Simplified Chinese (简体中文) <zh-cn.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[CN]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/CH.png "简体中文"

this file: © All Rights Reserved by zer0Kerbal

**Comment by ZhaoFJx** [comment]
@zer0Kerbal Maybe you should update this issue

**Comment by zer0Kerbal** [comment]
> @zer0Kerbal Maybe you should update this issue

Thank you - will auto close when I push the (pre)release today or tomorrow - depending upon compiling.

**Comment by zer0Kerbal** [comment]
@ZhaoFJx
 added strings after submitted - would you kindly update the file once I push this release? 🧧

**Comment by ZhaoFJx** [comment]
My bad, I haven't checked my inbox yesterday. Am I late?

**Comment by zer0Kerbal** [comment]
> My bad, I haven't checked my inbox yesterday. Am I late?

no no - you are just fine. I added/changed/corrected/sorted/linted `en-us.cfg`, then added the english strings to the `zh-cn.cfg`

If you are willing to update the `zh-cn.cfg` file, I made updating it as straightforward as possible.

**Comment by ZhaoFJx** [comment]
I will comprehensively update `zh-can.cfg` soon:)

**Comment by zer0Kerbal** [comment]
> I will comprehensively update `zh-can.cfg` soon:)

Thank you!
