### ISSUE TITLE
[Bug 🐞]: Incorrect mod settings descriptions/labels

### ISSUE THREAD

**Issue by johnnycocas** [zer0Kerbal/OhScrap#74]
### Brief description of your issue (aka the problem)

In-game mod settings are not being correctly mapped to the text keys in the Localization file, as shown in one of the attached print screens containing the contents of the DLL included in the mod.

### Operating system

Win10

### KSP version

1.12.3.3173

### Version of addon

2.2.0.0

### Steps to reproduce the behavior or issue

1. Open "Settings"
2. Open "Difficulty Options"
3. Select "OhScrap! (OHS) Options"

### Expected behavior

In-game settings text keys being mapped with the prefix "#OHS".

### Actual behavior

Settings keys are being mapped with the prefix "#FND".

### Environment

```shell
Mod: v2.2.0.0
KSP: v1.12.3.3173
Installation: CKAN
```

### Log files

[KSP.log](https://github.com/zer0Kerbal/OhScrap/files/9698979/KSP.log)

### Screenshots
In-game screenshot:
![image](https://user-images.githubusercontent.com/78932414/193619727-a1424ade-4432-4750-b1bc-5f690ab28ac9.png)

DLL contents:
![image](https://user-images.githubusercontent.com/78932414/193619939-b438431e-db7e-4a35-bc04-6d0c4c9a8fd9.png)

Localization file (expected values):
![image](https://user-images.githubusercontent.com/78932414/193620013-6129ec3b-f31c-41ba-b3ce-8742b31b0fe9.png)

### Additional context

Edited to add a label to each image.

### How did you download and install this?

CKAN (auto install with dependencies)

**Comment by zer0Kerbal** [comment]
@johnnycocas thank you for a wonderful bug report (the report is wonderful - not the bug)

**Comment by zer0Kerbal** [comment]
I believe this has been fixed internally - just not released (sooner than soon)

**Comment by johnnycocas** [comment]
Yeah the code in the repository seemed to be correct, at least on the 2.2.99.0 branch (master seemed to contain legacy code) so I assumed maybe the DLL was compiled with old code and said code was changed afterwards. Weird thing nonetheless, iirc "FND" should be for "Foundations", another of your mods, correct? Maybe some code found a way across to the other side 😁
